// react/maizuo_v2/src/component/common/NavBar.js
import React, { useContext } from 'react';
import './Nabbar.scss';
import AppContext from '../../AppContext';

function Navbar() {
  const context = useContext(AppContext);
  return (
    <nav id="toolbar">
      <h1>
        <a href="#" onClick={ context.toggleSideBar}>
          <div className="toolbar-title-icon">
            <i className="iconfont icon-list"></i>
          </div>
          <div className="toolbar-title">卖座电影</div>
        </a>
      </h1>
      <div id="nav-right">
        <a className="user">
          <i className="iconfont icon-user"></i>
        </a>
      </div>
    </nav>
  );
}

export default Navbar;

// angularMaizuo/src/app/components/common/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'nav-bar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.less']
})
export class NavBarComponent { }

<nav id="toolbar">
  <h1>
    <a href="javascript: void 0;">
      <div class="toolbar-title-icon">
        <i class="iconfont icon-list"></i>
      </div>
      <div class="toolbar-title">
        卖座电影
      </div>
    </a>
  </h1>
  <div id="nav-right">
    <a class="user">
      <i class="iconfont icon-user"></i>
    </a>
  </div>
</nav>
