// react/maizuo_v1/src/components/common/ImagePlaceholder.js
import React from 'react'

class ImagePlaceholder extends React.Component{

  render() {
    const {src,placeholder}=this.props
    const bgStyle={
      backgroundImage:'url('+placeholder+')',
      backgroundSize:100+'%'
    }
    return (
      <div class="img-responsive" style={bgStyle} >
        <img ref="image" src={src} onLoad={this.handleImageLoaded.bind(this)} style={{width : 100+'%',transition:'all 1.2s ease',opacity:0}} />
      </div>
    )
  }
  handleImageLoaded() {
    this.refs['image'].style.opacity=1
  }
}
export default ImagePlaceholder

// vue/maizuo_v3/src/components/image-placeholder.vue
<template>
  <div class="img-responsive" v-bind:style="{'background-image':'url('+placeholder+')'}" style="background-size:100%;">
    <img :src="src" v-on:load="loaded" style="width: 100%; transition: all 1.2s ease;"
         v-bind:style="{'opacity':finish?1:0}">
  </div>
</template>


<script>
  export default{
    data () {
      return {
        finish: false
      }
    },

    methods: {
      loaded () {
        const self = this
        setTimeout(function () {
          self.finish = true
        }, 100)
      }
    },
    props: {
      src: {
        type: String,
        required: true
      },
      placeholder: {
        type: String
      }
    }
  }
</script>
